export const STUDENTS_FETCH_START = Symbol('STUDENTS_FETCH_START');
export const STUDENTS_FETCH_SUCCESS = Symbol('STUDENTS_FETCH_SUCCESS');
export const STUDENTS_FETCH_FAILURE = Symbol('STUDENTS_FETCH_FAILURE');
export const FILTER_STUDENTS = Symbol('FILTER_STUDENTS');
