export const STUDENTS_FETCH_START = Symbol('STUDENTS_FETCH_START');
export const STUDENTS_FETCH_SUCCESS = Symbol('STUDENTS_FETCH_SUCCESS');
export const STUDENTS_FETCH_FAILURE = Symbol('STUDENTS_FETCH_FAILURE');
export const FILTER_STUDENTS_START = Symbol('FILTER_STUDENTS_START');
export const FILTER_STUDENTS_SUCCESS = Symbol('FILTER_STUDENTS_SUCCESS');
export const STUDENTDATA_FETCH_START = Symbol('STUDENTDATA_FETCH_START');
export const STUDENTDATA_FETCH_SUCCESS = Symbol('STUDENTDATA_FETCH_SUCCESS');
export const STUDENTDATA_FETCH_FAILURE = Symbol('STUDENTDATA_FETCH_FAILURE');

export const START_GET_Q = Symbol('START_GET_Q');
export const SUCCESS_GET_Q = Symbol('SUCCESS_GET_Q');
export const FAIL_GET_Q = Symbol('FAIL_GET_Q');

export const START_LOGIN = Symbol('START_LOGIN');
export const SUCCESS_LOGIN = Symbol('SUCCESS_LOGIN');
export const FAILURE_LOGIN = Symbol('FAILURE_LOGIN');

export const STORE_ANSWER = Symbol(' STORE_ANSWER');
export const STORE_DATA_FAILURE = Symbol(' STORE_ANSWER');

export const SUCCESS_GET_USERID = Symbol('SUCCESS_GET_USERID');
export const FAILURE_GET_USERID = Symbol('FAILURE_GET_USERID');
